cat "$BUILT_PRODUCTS_DIR/include/$PRODUCT_NAME/$PRODUCT_NAME.h" >> "$BUILT_PRODUCTS_DIR/include/$PRODUCT_NAME/tmp.txt"
echo "#define IPHONE 1" > "$BUILT_PRODUCTS_DIR/include/$PRODUCT_NAME/$PRODUCT_NAME.h"
cat "$BUILT_PRODUCTS_DIR/include/$PRODUCT_NAME/tmp.txt" >> "$BUILT_PRODUCTS_DIR/include/$PRODUCT_NAME/$PRODUCT_NAME.h"
rm -rf "$BUILT_PRODUCTS_DIR/include/$PRODUCT_NAME/tmp.txt"